version: '3.8'

services:

  backend:
    build: ./Backend
    ports:
      - "8080:8080"
    environment:
      SPRING_MAIL_USERNAME: ACA-VA-MI-EMAIL
      SPRING_MAIL_PASSWORD: MI-CONTRA-DE-APLICACION

  frontend:
    build: ./Frontend
    ports:
      - "80:80"
    depends_on:
      - backend
